import Head from "next/head";
import Image from "next/image";
import React from "react";
import GYM from "../public/assets/projects/fitness.png";
import { RiRadioButtonFill } from "react-icons/ri";
import Link from "next/link";

const gym = () => {
  return (
    <div>
      <Head>
        <title>PROJECTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="w-screen h-[30vh] lg:h-[40vh] relative">
          <div className="absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/50 z-10" />
          <Image
            className="absolute z-1"
            src={GYM}
            layout="fill"
            objectFit="cover"
            alt="gym"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">GYM</h2>
            <h3>HTML / CSS/ JAVASCRIPT</h3>
          </div>
        </div>
        <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 pt-8">
          <div className="col-span-4">
            <p>Project</p>
            <h2>Overview</h2>
            <p>
              This app was created with CSS, JS, and HTML and is hosted on
              Netlify. I was working on a basic landing page that discussed the
              workouts to be done, the best trainers to use, and the special
              diet to be followed. What I discovered: Create a responsive navbar
              with pure javascript, learn the difference between flex box and
              grid and where to use them, and have some fun with hover
              transitions in my application. Using the buttons below, you can
              view the application's demo and source code.
            </p>
            <button className="px-8 py-2 mt-4 mr-8">
              <a target="_blank" rel="noreferrer" href="https://gymbykim.netlify.app/">
                Demo
              </a>
            </button>
            <button className="px-8 py-2 mt-4">
              <a
                target="_blank"
                rel="noreferrer"
                href="https://github.com/Rotich2000/gym-landing"
              >
                Code
              </a>
            </button>
          </div>
          <div className="col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4">
            <div className="p-2">
              <p className="text-center font-bold pb-2">Technologies</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> HTML{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> CSS{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> JAVASCRIPT{" "}
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="underline cursor-pointer text-center">Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default gym;
