import Head from "next/head";
import Image from "next/image";
import React from "react";
import Airbnb from "../public/assets/projects/airbnb.png";
import { RiRadioButtonFill } from "react-icons/ri";
import Link from "next/link";

const property = () => {
  return (
    <div>
      <Head>
        <title>PROJECTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="w-screen h-[30vh] lg:h-[40vh] relative">
          <div className="absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/50 z-10" />
          <Image
            className="absolute z-1"
            src={Airbnb}
            layout="fill"
            objectFit="cover"
            alt="property"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Airbnb</h2>
            <h3>Next JS / Tailwind / Mapbox</h3>
          </div>
        </div>
        <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 pt-8">
          <div className="col-span-4">
            <p>Project</p>
            <h2>Overview</h2>
            <p>
              This app was built using Next JS and is hosted on Vercel. Users
              are able to search for Rooms located in various cities. You will
              be able to view property information as well as the specific
              location of the rooms intergrated with Mapbox API.
            </p>
            <button className="px-8 py-2 mt-4 mr-8"><a target="_blank" rel="noopener noreferrer" href="https://airbnb-demo-b49k-flg9mluxe-rotich2000.vercel.app/">Demo</a></button>
            <button className="px-8 py-2 mt-4"><a target="_blank" rel="noopener noreferrer" href="https://github.com/Rotich2000/airbnb-demo">Code</a></button>
          </div>
          <div className="col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4">
            <div className="p-2">
              <p className="text-center font-bold pb-2">Technologies</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> React{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> Next{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> Tailwind{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> Javascript{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> MapBox{" "}
                </p>
              </div>
            </div>
          </div>
        <Link href='/#projects'>
            <p className="underline cursor-pointer text-center">Back</p>
        </Link>
        </div>
      </div>
    </div>
  );
};

export default property;
