import Head from "next/head";
import Image from "next/image";
import React from "react";
import Sushi from "../public/assets/projects/sushi.png";
import { RiRadioButtonFill } from "react-icons/ri";
import Link from "next/link";

const sushi = () => {
  return (
    <div>
      <Head>
        <title>PROJECTS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full">
        <div className="w-screen h-[30vh] lg:h-[40vh] relative">
          <div className="absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/50 z-10" />
          <Image
            className="absolute z-1"
            src={Sushi}
            layout="fill"
            objectFit="cover"
            alt="sushi"
          />
          <div className="absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2">
            <h2 className="py-2">Sushi</h2>
            <h3>Next JS / Tailwind / Mapbox</h3>
          </div>
        </div>
        <div className="max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 pt-8">
          <div className="col-span-4">
            <p>Project</p>
            <h2>Overview</h2>
            <p>
              This application was created entirely in CSS, HTML, and
              JavaScript. This is what I discovered about the landing page for
              sushi: Create a website that is fully responsive using javascript
              and CSS. Pure vanilla javascript can be used to add a box shadow
              on scroll, In order to improve the scroll animation on my
              application, I created a dark and light theme using CSS and
              Javascript. To view the web page and the source code, simply click
              the buttons.
            </p>
            <button className="px-8 py-2 mt-4 mr-8">
              <a target="_blank" rel="noopener noreferrer" href="https://foodbykim.netlify.app/">
                Demo
              </a>
            </button>
            <button className="px-8 py-2 mt-4">
              <a target="_blank" rel="noopener noreferrer" href="https://github.com/Rotich2000/hotel">
                Code
              </a>
            </button>
          </div>
          <div className="col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4">
            <div className="p-2">
              <p className="text-center font-bold pb-2">Technologies</p>
              <div className="grid grid-cols-3 md:grid-cols-1">
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> HTML{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> CSS{" "}
                </p>
                <p className="text-gray-600 py-2 flex items-center">
                  {" "}
                  <RiRadioButtonFill className="pr-1" /> Javascript{" "}
                </p>
              </div>
            </div>
          </div>
          <Link href="/#projects">
            <p className="underline cursor-pointer text-center">Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default sushi;
